# Generated by Django 3.2.5 on 2021-07-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exec_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
