# Generated by Django 3.2.5 on 2021-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_exec_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
