# Generated by Django 3.2.5 on 2021-07-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_exec_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
