# Generated by Django 4.1.4 on 2023-02-15 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("folder", models.CharField(blank=True, max_length=200, null=True)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                (
                    "bridge_port",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=256, null=True)),
                ("password", models.CharField(blank=True, max_length=256, null=True)),
                ("connection", models.CharField(blank=True, max_length=256, null=True)),
                ("groups", models.ManyToManyField(blank=True, to="auth.group")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
