# Generated by Django 4.1.3 on 2022-12-02 07:36

import apps.core.system
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("folder", models.CharField(blank=True, max_length=200, null=True)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        upload_to=apps.core.system.get_upload_to,
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=16, null=True)),
                ("topic", models.CharField(blank=True, max_length=200, null=True)),
                ("fields", models.CharField(blank=True, max_length=4096, null=True)),
                (
                    "published",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="publish now"
                    ),
                ),
                ("groups", models.ManyToManyField(blank=True, to="auth.group")),
            ],
        ),
    ]
